version: '3.8'
services:
  app:
    image: "node:16"
    ports:
     - "3100:3100"
    command: "yarn dev"
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
volumes:
  node_modules:
